'use client'

import Link from 'next/link'
import { ArrowLeft, RefreshCw } from 'lucide-react'
import { useApi } from '@/lib/hooks'
import { useAdminPrompt } from './AdminPromptDialog'

type Detail = { application: { id: number; userId: string; jobId: string; status: string; mode: string; atsType: string; flowUsed: string; errorClass: string | null; durationMs: number | null; createdAt: string; taskId: string | null; taskStatus: string | null; checkpoint: string | null }; task: { id: string; status: string; checkpoint: string | null; errorClass: string | null; startedAt: string | null; completedAt: string | null; events: Array<{ id: string; type: string; actor: string; body: string; createdAt: string }> } | null }

export function AdminApplicationDetailPage({ applicationId, permissions }: { applicationId: string; permissions: readonly string[] }) {
  const { data, loading, error, refetch } = useApi<Detail>(`/api/admin/v1/applications/${applicationId}`)
  const { request, dialog } = useAdminPrompt()
  const application = data?.application
  async function act(action: 'retry' | 'cancel' | 'manual_review') {
    if (!data?.task?.id) return
    const reason = await request({ title: 'Confirm application action', label: 'Operational reason', kind: 'reason', description: 'This action and its reason will be retained in the administrator audit log.', submitLabel: 'Continue' })
    if (!reason) return
    const response = await fetch(`/api/admin/v1/applications/${data.task.id}/action`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ action, reason }) })
    if (response.ok) await refetch()
  }
  return <><div className="admin-page"><header className="admin-header"><div><Link prefetch={false} className="admin-back" href="/admin/applications"><ArrowLeft size={16} /> Applications</Link><h1>Application detail</h1><p>Safe execution metadata and task history</p></div><button className="admin-secondary" type="button" onClick={() => void refetch()}><RefreshCw size={14} /> Refresh</button></header>{error && <div className="admin-alert">{error}</div>}{loading && !application && <div className="admin-placeholder"><section>Loading application…</section></div>}{application && <div className="admin-detail"><section className="admin-detail-grid"><section><h2>Result</h2><dl><dt>ID</dt><dd>{application.id}</dd><dt>Status</dt><dd>{application.status}</dd><dt>Mode</dt><dd>{application.mode}</dd><dt>ATS</dt><dd>{application.atsType}</dd><dt>Flow</dt><dd>{application.flowUsed}</dd><dt>Error class</dt><dd>{application.errorClass ?? '—'}</dd><dt>Duration</dt><dd>{application.durationMs == null ? '—' : `${Math.round(application.durationMs / 1000)}s`}</dd><dt>Created</dt><dd>{new Date(application.createdAt).toLocaleString()}</dd></dl></section><section><h2>Execution task</h2><dl><dt>Task ID</dt><dd>{application.taskId ?? '—'}</dd><dt>Status</dt><dd>{application.taskStatus ?? '—'}</dd><dt>Checkpoint</dt><dd>{application.checkpoint ?? '—'}</dd><dt>Error class</dt><dd>{data.task?.errorClass ?? '—'}</dd><dt>Candidate</dt><dd>{application.userId}</dd><dt>Job</dt><dd>{application.jobId}</dd></dl><div className="admin-action-group" style={{ marginTop: 18 }}>{permissions.includes('applications.retry') && data.task && ['failed', 'cancelled'].includes(data.task.status) && <button className="admin-secondary" type="button" onClick={() => void act('retry')}>Retry</button>}{permissions.includes('applications.manual_review') && data.task && !['submitted', 'cancelled'].includes(data.task.status) && <button className="admin-secondary" type="button" onClick={() => void act('manual_review')}>Manual review</button>}{permissions.includes('applications.cancel') && data.task && !['submitted', 'skipped', 'cancelled'].includes(data.task.status) && <button className="admin-secondary" type="button" onClick={() => void act('cancel')}>Cancel</button>}</div></section></section><section className="admin-detail-history"><h2>Task events</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Time</th><th>Type</th><th>Actor</th><th>Safe note</th></tr></thead><tbody>{data.task?.events.length ? data.task.events.map(event => <tr key={event.id}><td>{new Date(event.createdAt).toLocaleString()}</td><td>{event.type}</td><td>{event.actor}</td><td>{event.body}</td></tr>) : <tr><td colSpan={4}>No task events.</td></tr>}</tbody></table></div></section></div>}</div>{dialog}</>
}
