'use client'

import React, { useEffect, useState } from 'react'
import { Ban, Eye, Megaphone, RefreshCw, Send, Sparkles } from 'lucide-react'
import { useI18n } from '@/lib/i18n'

interface Broadcast { id: string; title: string; body: string; audienceType: string; audience: { plan?: string; location?: string; userIds?: string[] }; status: string; scheduledAt: string | null; recipientCount: number; deliveredCount: number; failedCount: number; createdAt: string; updatedAt: string }
export function audienceLabel(value: Pick<Broadcast, 'audienceType' | 'audience'>, t?: (key: string) => string): string { if (value.audienceType === 'all_active_users') return t?.('broadcasts.allActive') ?? 'All active users'; if (value.audienceType === 'plan') return `${capitalize(value.audience.plan ?? t?.('broadcasts.unknown') ?? 'Unknown')} ${t?.('broadcasts.plan') ?? 'plan'}`; if (value.audienceType === 'location') return value.audience.location ?? t?.('broadcasts.location') ?? 'Location'; return `${value.audience.userIds?.length ?? 0} ${t?.('broadcasts.selectedAccounts') ?? 'selected accounts'}` }
export function broadcastActionLabel(status: string, t?: (key: string) => string): string { return status === 'draft' ? t?.('broadcasts.submitApproval') ?? 'Submit for approval' : status === 'scheduled' ? t?.('broadcasts.publish') ?? 'Publish' : t?.('broadcasts.noAction') ?? 'No action' }

function capitalize(value: string): string { return value ? `${value[0].toUpperCase()}${value.slice(1)}` : value }

export function BroadcastsPage() {
  const { t } = useI18n()
  const [items, setItems] = useState<Broadcast[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [showCreate, setShowCreate] = useState(false)
  async function load() { setLoading(true); setError(''); try { const response = await fetch('/api/admin/v1/broadcasts', { cache: 'no-store' }); const body = await response.json() as { items?: Broadcast[]; error?: string }; if (!response.ok) throw new Error(body.error ?? t('broadcasts.loadFailed')); setItems(body.items ?? []) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : t('broadcasts.loadFailed')) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  return <div style={{ maxWidth: 1180, margin: '0 auto' }}><header style={headerStyle}><div><div style={eyebrow}>{t('broadcasts.eyebrow')}</div><h1 style={titleStyle}>{t('broadcasts.title')}</h1><p style={muted}>{t('broadcasts.description')}</p></div><div style={buttonRow}><button type="button" title={t('broadcasts.refresh')} onClick={() => void load()} style={iconButton}><RefreshCw size={16} aria-hidden="true" /></button><button type="button" onClick={() => setShowCreate(value => !value)} style={primary}><Megaphone size={15} aria-hidden="true" /> {t('broadcasts.new')}</button></div></header>{error && <ErrorBox text={error} />}{showCreate && <CreateBroadcast onCreated={async () => { setShowCreate(false); await load() }} />}{loading ? <p style={muted}>{t('broadcasts.loading')}</p> : <section style={section}><div style={{ overflowX: 'auto' }}><table style={table}><thead><tr><th>{t('broadcasts.message')}</th><th>{t('broadcasts.audience')}</th><th>{t('broadcasts.status')}</th><th>{t('broadcasts.delivery')}</th><th /></tr></thead><tbody>{items.map(item => <BroadcastRow key={item.id} item={item} onChanged={load} />)}</tbody></table></div>{items.length === 0 && <p style={muted}>{t('broadcasts.empty')}</p>}</section>}</div>
}

function CreateBroadcast({ onCreated }: { onCreated: () => Promise<void> }) {
  const { t } = useI18n()
  const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [audienceType, setAudienceType] = useState('all_active_users'); const [plan, setPlan] = useState('pro'); const [location, setLocation] = useState(''); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false)
  async function create() { if (!title.trim() || !body.trim() || reason.trim().length < 10) return; setBusy(true); try { const response = await fetch('/api/admin/v1/broadcasts', { method: 'POST', headers: headers(), body: JSON.stringify({ title, body, audienceType, plan: audienceType === 'plan' ? plan : undefined, location: audienceType === 'location' ? location : undefined, reason }) }); if (!response.ok) throw new Error(t('broadcasts.createFailed')); await onCreated() } finally { setBusy(false) } }
  return <section style={section}><h2 style={heading}>{t('broadcasts.newDraft')}</h2><div style={formGrid}><input value={title} onChange={event => setTitle(event.target.value)} placeholder={t('broadcasts.titleLabel')} style={input} /><select value={audienceType} onChange={event => setAudienceType(event.target.value)} style={input}><option value="all_active_users">{t('broadcasts.allActive')}</option><option value="plan">{t('broadcasts.plan')}</option><option value="location">{t('broadcasts.location')}</option></select>{audienceType === 'plan' && <select value={plan} onChange={event => setPlan(event.target.value)} style={input}><option value="free">Free</option><option value="pro">Pro</option><option value="enterprise">Enterprise</option></select>}{audienceType === 'location' && <input value={location} onChange={event => setLocation(event.target.value)} placeholder={t('broadcasts.location')} style={input} />}<textarea value={body} onChange={event => setBody(event.target.value)} placeholder={t('broadcasts.message')} rows={4} style={{ ...input, padding: 8, gridColumn: '1 / -1', resize: 'vertical' as const }} /><input value={reason} onChange={event => setReason(event.target.value)} placeholder={t('broadcasts.auditReason')} style={input} /><button type="button" disabled={busy || reason.trim().length < 10} onClick={() => void create()} style={primary}><Sparkles size={14} aria-hidden="true" /> {t('broadcasts.saveDraft')}</button></div></section>
}

function BroadcastRow({ item, onChanged }: { item: Broadcast; onChanged: () => Promise<void> }) {
  const { t } = useI18n()
  const [preview, setPreview] = useState<{ recipientCount: number } | null>(null); const [busy, setBusy] = useState(false)
  async function action(kind: 'submit' | 'approve' | 'publish' | 'cancel') { const reason = window.prompt(t('broadcasts.reasonPrompt'))?.trim() ?? ''; if (reason.length < 10) return; if (kind === 'publish' && !window.confirm(t('broadcasts.publishConfirm'))) return; setBusy(true); try { const response = await fetch(`/api/admin/v1/broadcasts/${item.id}/${kind}`, { method: 'POST', headers: headers(), body: JSON.stringify({ reason, confirm: kind === 'publish' }) }); if (!response.ok) { const body = await response.json() as { error?: string }; window.alert(body.error ?? t('broadcasts.actionFailed')) } else await onChanged() } finally { setBusy(false) } }
  async function showPreview() { const response = await fetch(`/api/admin/v1/broadcasts/${item.id}/preview`, { method: 'POST', headers: headers(), body: '{}' }); if (response.ok) setPreview(await response.json() as { recipientCount: number }) }
  return <tr><td><strong>{item.title}</strong><span style={sub}>{item.body.slice(0, 90)}{item.body.length > 90 ? '…' : ''}</span></td><td>{audienceLabel(item, t)}<button type="button" title={t('broadcasts.preview')} onClick={() => void showPreview()} style={iconButton}><Eye size={14} aria-hidden="true" /></button>{preview && <span style={sub}>{preview.recipientCount} {t('broadcasts.recipients')}</span>}</td><td><span style={status}>{item.status}</span></td><td>{item.deliveredCount}/{item.recipientCount}{item.failedCount ? ` · ${item.failedCount} ${t('broadcasts.failed')}` : ''}</td><td><div style={buttonRow}>{item.status === 'draft' && <button type="button" disabled={busy} onClick={() => void action('submit')} style={smallButton}><Send size={13} aria-hidden="true" /> {t('broadcasts.submitApproval')}</button>}{item.status === 'pending_approval' && <button type="button" disabled={busy} onClick={() => void action('approve')} style={smallButton}><Send size={13} aria-hidden="true" /> {t('broadcasts.approve')}</button>}{item.status === 'scheduled' && <button type="button" disabled={busy} onClick={() => void action('publish')} style={smallButton}><Send size={13} aria-hidden="true" /> {t('broadcasts.publish')}</button>}{['draft', 'pending_approval', 'scheduled'].includes(item.status) && <button type="button" disabled={busy} onClick={() => void action('cancel')} style={smallButton}><Ban size={13} aria-hidden="true" /> {t('common.cancel')}</button>}</div></td></tr>
}

function headers(): HeadersInit { return { 'Content-Type': 'application/json', Origin: window.location.origin, 'Idempotency-Key': `${Date.now()}-${Math.random().toString(36).slice(2)}` } }
function ErrorBox({ text }: { text: string }) { return <div role="alert" style={{ marginBottom: 14, padding: 10, border: '1px solid #e6b8b8', color: '#a32d2d', background: '#fff8f8', borderRadius: 6 }}>{text}</div> }
const headerStyle = { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16, marginBottom: 22 }
const eyebrow = { color: '#5b6b80', fontSize: 11, textTransform: 'uppercase' as const, letterSpacing: '.08em' }
const titleStyle = { margin: '5px 0 0', fontSize: 28 }
const muted = { color: '#5b6b80', fontSize: 12 }
const sub = { display: 'block', color: '#687b90', fontSize: 11, marginTop: 4, maxWidth: 300 }
const section = { background: '#fff', border: '1px solid #d9e2ec', borderRadius: 8, padding: 18, marginBottom: 16 }
const heading = { margin: '0 0 14px', fontSize: 16 }
const formGrid = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(170px,1fr))', gap: 8 }
const input = { minHeight: 34, minWidth: 0, border: '1px solid #c9d5e1', borderRadius: 5, padding: '0 9px', background: '#fff', color: '#172033', font: 'inherit' }
const table = { width: '100%', borderCollapse: 'collapse' as const, fontSize: 12 }
const status = { display: 'inline-block', padding: '3px 7px', borderRadius: 999, background: '#eef1f5', color: '#5b6b80', fontSize: 11, fontWeight: 700 }
const buttonRow = { display: 'flex', flexWrap: 'wrap' as const, gap: 6, alignItems: 'center' }
const primary = { minHeight: 34, display: 'inline-flex', alignItems: 'center', gap: 6, border: 0, borderRadius: 6, padding: '0 12px', background: '#146c94', color: '#fff', cursor: 'pointer', fontWeight: 700, fontSize: 12 }
const smallButton = { minHeight: 30, display: 'inline-flex', alignItems: 'center', gap: 4, border: '1px solid #c9d5e1', borderRadius: 5, background: '#fff', color: '#146c94', cursor: 'pointer', padding: '0 8px', fontSize: 11 }
const iconButton = { width: 30, height: 30, display: 'inline-grid', placeItems: 'center', border: '1px solid #c9d5e1', borderRadius: 5, background: '#fff', cursor: 'pointer', marginLeft: 5 }
