/**
 * Dry-run verification harness for ATS apply flows.
 *
 * Runs a pre-programmed flow against a real apply URL in dry-run mode,
 * takes a screenshot at the final step, and writes a machine-readable report.
 *
 * Usage:
 *   pnpm --filter worker exec tsx scripts/verify-flow.ts greenhouse https://boards.greenhouse.io/booking/jobs/123456
 *   pnpm --filter worker exec tsx scripts/verify-flow.ts smartrecruiters https://jobs.smartrecruiters.com/Visa/744000129815717
 *   pnpm --filter worker exec tsx scripts/verify-flow.ts personio https://flixbus.jobs.personio.com/job/123
 *   pnpm --filter worker exec tsx scripts/verify-flow.ts lever https://jobs.lever.co/spotify/abc123
 *   pnpm --filter worker exec tsx scripts/verify-flow.ts workday https://siemens.wd3.myworkdayjobs.com/Siemens/job/123
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { withCloakContext } from "../src/cloak/pool.js";
import { detectFlow } from "../src/flows/index.js";
import { runGreenhouseFlow } from "../src/flows/greenhouse-flow.js";
import { runLeverFlow } from "../src/flows/lever-flow.js";
import { runPersonioFlow } from "../src/flows/personio-flow.js";
import { runSmartRecruitersFlow } from "../src/flows/smartrecruiters-flow.js";
import { runWorkdayFlow } from "../src/flows/workday-flow.js";
import type { ApplyTask, HarnessResult } from "../src/harness/agent-harness.js";

const VALID_ATS = ["greenhouse", "lever", "workday", "smartrecruiters", "personio"] as const;
type VerifiableAts = (typeof VALID_ATS)[number];

function mockPersona(): Record<string, string> {
  return {
    fullName: "Test User",
    firstName: "Test",
    lastName: "User",
    email: "verify@applymate.dev",
    phone: "+49 123 456789",
    location: "Berlin, Germany",
    linkedinUrl: "https://linkedin.com/in/test",
    coverLetter: "This is a verification cover letter generated by the ApplyMate dry-run harness. Please ignore.",
  };
}

function isVerifiableAts(value: string): value is VerifiableAts {
  return VALID_ATS.includes(value as VerifiableAts);
}

function usage(): void {
  console.error("Usage: pnpm --filter worker exec tsx scripts/verify-flow.ts <ats> <url>");
  console.error(`  <ats>: ${VALID_ATS.join(" | ")}`);
  console.error("  <url>: Full apply URL for a real job posting");
  console.error("");
  console.error("Examples:");
  console.error("  pnpm --filter worker exec tsx scripts/verify-flow.ts greenhouse https://boards.greenhouse.io/booking/jobs/123");
  console.error("  pnpm --filter worker exec tsx scripts/verify-flow.ts smartrecruiters https://jobs.smartrecruiters.com/Visa/744000129815717");
  console.error("  pnpm --filter worker exec tsx scripts/verify-flow.ts personio https://flixbus.jobs.personio.com/job/123");
}

async function runFlow(
  ats: VerifiableAts,
  page: Parameters<typeof runGreenhouseFlow>[0],
  task: ApplyTask
): Promise<HarnessResult> {
  if (ats === "greenhouse") return runGreenhouseFlow(page, task);
  if (ats === "lever") return runLeverFlow(page, task);
  if (ats === "workday") return runWorkdayFlow(page, task);
  if (ats === "personio") return runPersonioFlow(page, task);
  return runSmartRecruitersFlow(page, task);
}

function summarizeFields(log: unknown[] | undefined): string {
  if (!log?.length) return "(none)";

  const fields = log
    .filter((entry): entry is { field?: string; action?: string } => {
      return Boolean(entry && typeof entry === "object" && "action" in entry);
    })
    .filter((entry) => ["fill", "upload", "fill-custom"].includes(String(entry.action)))
    .map((entry) => entry.field ?? entry.action ?? "unknown");

  return fields.length ? fields.join(", ") : "(none)";
}

async function main(): Promise<void> {
  const [atsArg, url] = process.argv.slice(2);

  if (!atsArg || !url) {
    usage();
    process.exit(1);
  }

  const explicitAts = atsArg.toLowerCase();
  const detected = detectFlow(url);
  const flow = detected ?? explicitAts;

  if (!isVerifiableAts(flow)) {
    console.error(`Unknown ATS "${flow}". Supported: ${VALID_ATS.join(", ")}`);
    process.exit(1);
  }

  console.log(`Verifying ${flow} flow against ${url}`);
  if (detected && detected !== explicitAts) {
    console.log(`URL detector selected ${detected}; explicit arg was ${explicitAts}`);
  }

  const startedAt = Date.now();

  await withCloakContext("verify-user", async (page) => {
    console.log("Navigating...");
    await page.goto(url, {
      waitUntil: "domcontentloaded",
      timeout: 30_000,
    });

    const task: ApplyTask = {
      jobId: `verify-${Date.now()}`,
      applyUrl: url,
      persona: mockPersona(),
      jobTitle: "Verification Job",
      jobCompany: "Verification Company",
      resumePath: "",
      dryRun: true,
    };

    console.log(`Running ${flow} flow in dry-run mode...`);
    const result = await runFlow(flow, page, task);

    const dir = ".tmp/verify";
    mkdirSync(dir, { recursive: true });
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const screenshotPath = `${dir}/${flow}-${timestamp}.png`;
    await page.screenshot({ path: screenshotPath, fullPage: false });

    const durationMs = result.durationMs ?? Date.now() - startedAt;
    const reportPath = `${dir}/${flow}-${timestamp}.json`;
    writeFileSync(
      reportPath,
      JSON.stringify(
        {
          flow,
          url,
          status: result.status,
          durationMs,
          turns: result.turns,
          error: result.error ?? null,
          log: result.log ?? [],
          screenshotPath,
        },
        null,
        2
      ),
      "utf-8"
    );

    console.log("");
    console.log("--- Verification Summary ---");
    console.log(`ATS:             ${flow}`);
    console.log(`Status:          ${result.status}`);
    console.log(`Filled fields:   ${summarizeFields(result.log)}`);
    console.log(`Duration:        ${durationMs}ms`);
    console.log(`Screenshot path: ${screenshotPath}`);
    console.log(`Report path:     ${reportPath}`);
    if (result.error) console.log(`Error:           ${result.error}`);
    console.log("----------------------------");
  });

  process.exit(0);
}

main().catch((err: unknown) => {
  console.error("Verification failed:", err instanceof Error ? err.message : String(err));
  process.exit(1);
});
