import { db } from '@/lib/db'
import { requireAdmin } from '@/lib/admin/authorization'
import { writeAdminAudit } from '@/lib/admin/audit'
import { validateAdminWriteRequest } from '@/lib/admin/csrf'
import { withAdminIdempotency } from '@/lib/admin/idempotency'
import { storedAudience } from '../../route'
import { broadcastWhere } from '@/lib/admin/broadcast'
import { adminError, adminJson, jsonBody, requestId, requiredIdempotencyKey, requiredReason } from '@/lib/admin/route-utils'

export async function POST(request: Request, context: { params: Promise<{ id: string }> }) {
  const correlationId = requestId(request)
  try { const actor = await requireAdmin('broadcasts.publish', request); const csrf = validateAdminWriteRequest(request); if (!csrf.ok) return adminJson({ error: csrf.code }, csrf.status, correlationId); const { id } = await context.params; const body = await jsonBody(request); const reason = requiredReason(body); if (body.confirm !== true) return adminJson({ error: 'BROADCAST_CONFIRMATION_REQUIRED' }, 400, correlationId); const current = await db.adminBroadcast.findUnique({ where: { id }, select: { id: true, status: true, createdById: true, audienceType: true, audience: true, title: true, body: true } }); if (!current) return adminJson({ error: 'BROADCAST_NOT_FOUND' }, 404, correlationId); if (current.createdById === actor.userId) return adminJson({ error: 'BROADCAST_CREATOR_CANNOT_PUBLISH' }, 403, correlationId); if (current.status !== 'scheduled') return adminJson({ error: 'BROADCAST_STATUS_INVALID' }, 409, correlationId); const idempotencyKey = requiredIdempotencyKey(request); const response = await withAdminIdempotency(db, { actorUserId: actor.userId, key: idempotencyKey, action: 'admin.broadcast.publish', body: { id, reason } }, async transaction => { const users = await transaction.user.findMany({ where: broadcastWhere(storedAudience(current)), select: { id: true } }); const result = await transaction.notification.createMany({ data: users.map(user => ({ userId: user.id, broadcastId: id, type: 'platform_broadcast', title: current.title, body: current.body })), skipDuplicates: true }); const broadcast = await transaction.adminBroadcast.update({ where: { id, status: 'scheduled' }, data: { status: 'published', publishedById: actor.userId, recipientCount: users.length, deliveredCount: result.count, failedCount: 0 }, select: { id: true, status: true, recipientCount: true, deliveredCount: true } }); await writeAdminAudit(transaction, { requestId: correlationId, actorUserId: actor.userId, actorRoleKey: actor.roleKey, action: 'admin.broadcast.publish', targetType: 'broadcast', targetId: id, reason, outcome: 'success', after: { status: broadcast.status, recipientCount: broadcast.recipientCount, deliveredCount: broadcast.deliveredCount } }); return { status: 200, body: { broadcast } } }); return adminJson(response.body, response.status, correlationId) } catch (error) { return adminError(error, correlationId) }
}
