import { db } from '@/lib/db'
import { requireAdmin } from '@/lib/admin/authorization'
import { writeAdminAudit } from '@/lib/admin/audit'
import { validateAdminWriteRequest } from '@/lib/admin/csrf'
import { withAdminIdempotency } from '@/lib/admin/idempotency'
import { adminError, adminJson, jsonBody, requestId, requiredIdempotencyKey, requiredReason } from '@/lib/admin/route-utils'

export async function POST(request: Request, context: { params: Promise<{ id: string }> }) {
  const correlationId = requestId(request)
  try { const actor = await requireAdmin('broadcasts.approve', request); const csrf = validateAdminWriteRequest(request); if (!csrf.ok) return adminJson({ error: csrf.code }, csrf.status, correlationId); const { id } = await context.params; const body = await jsonBody(request); const reason = requiredReason(body); const current = await db.adminBroadcast.findUnique({ where: { id }, select: { id: true, status: true, createdById: true } }); if (!current) return adminJson({ error: 'BROADCAST_NOT_FOUND' }, 404, correlationId); if (current.createdById === actor.userId) return adminJson({ error: 'BROADCAST_CREATOR_CANNOT_APPROVE' }, 403, correlationId); if (current.status !== 'pending_approval') return adminJson({ error: 'BROADCAST_STATUS_INVALID' }, 409, correlationId); const idempotencyKey = requiredIdempotencyKey(request); const response = await withAdminIdempotency(db, { actorUserId: actor.userId, key: idempotencyKey, action: 'admin.broadcast.approve', body: { id, reason } }, async transaction => { const broadcast = await transaction.adminBroadcast.update({ where: { id }, data: { status: 'scheduled', approvedById: actor.userId }, select: { id: true, status: true, approvedById: true } }); await writeAdminAudit(transaction, { requestId: correlationId, actorUserId: actor.userId, actorRoleKey: actor.roleKey, action: 'admin.broadcast.approve', targetType: 'broadcast', targetId: id, reason, outcome: 'success', after: { status: broadcast.status, approvedById: broadcast.approvedById } }); return { status: 200, body: { broadcast } } }); return adminJson(response.body, response.status, correlationId) } catch (error) { return adminError(error, correlationId) }
}
